### ISSUE TITLE
Function deprecated

### ISSUE THREAD

**Issue by tlubitz** [devmount/GermanWordEmbeddings#1]
The training.py contains a deprecated word2vec function for saving the model after training:

```
Traceback (most recent call last):
  File "training.py", line 56, in <module>
    model.save_word2vec_format(args.target, binary=True)
  File "/home/timo/.local/lib/python2.7/site-packages/gensim/models/word2vec.py", line 1312, in save_word2vec_format
    raise DeprecationWarning("Deprecated. Use model.wv.save_word2vec_format instead.")
DeprecationWarning: Deprecated. Use model.wv.save_word2vec_format instead.
```

This should be updated.

**Comment by devmount** [comment]
Thanks for pointing this out,
Fixed in PR https://github.com/devmount/GermanWordEmbeddings/pull/2
