### ISSUE TITLE
UnpicklingError beim verwenden deines Models

### ISSUE THREAD

**Issue by mariisaschmidt** [devmount/GermanWordEmbeddings#27]
Hey 👋 
ich versuche zurzeit einen Sarkasmus Klassifizieren ( [Link](https://bitbucket.org/rklinger/adversarialsatire/src/master/)) zum Laufen zu bekommen. Ich habe den Code und den Originalkorpus, allerdings fehlt mir das deutsche w2v Model, um die Merkmalsvektoren zu generieren. 
Nach etwas googeln habe ich dein Model (german.model) gefunden. Allerdings bekomme ich folgende Fehlermeldung wenn ich es in den Code einbinde: 
```
Traceback (most recent call last):
  File "/Users/marisaschmidt/Desktop/sarcasm-detection/Classifiers/adversialsatire/src/classifier.py", line 6, in <module>
    import keras, retriever, argparse, os, numpy, evaluation, feature_extractors
  File "/Users/marisaschmidt/Desktop/sarcasm-detection/Classifiers/adversialsatire/src/retriever.py", line 6, in <module>
    import os, feature_extractors, numpy, classifier, random, sqlite3
  File "/Users/marisaschmidt/Desktop/sarcasm-detection/Classifiers/adversialsatire/src/feature_extractors.py", line 14, in <module>
    vector_model = gensim.models.Word2Vec.load(w2v_model).wv
  File "/opt/anaconda3/envs/ba/lib/python3.6/site-packages/gensim/models/word2vec.py", line 975, in load
    return super(Word2Vec, cls).load(*args, **kwargs)
  File "/opt/anaconda3/envs/ba/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 629, in load
    model = super(BaseWordEmbeddingsModel, cls).load(*args, **kwargs)
  File "/opt/anaconda3/envs/ba/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 278, in load
    return super(BaseAny2VecModel, cls).load(fname_or_handle, **kwargs)
  File "/opt/anaconda3/envs/ba/lib/python3.6/site-packages/gensim/utils.py", line 425, in load
    obj = unpickle(fname)
  File "/opt/anaconda3/envs/ba/lib/python3.6/site-packages/gensim/utils.py", line 1332, in unpickle
    return _pickle.load(f, encoding='latin1')
_pickle.UnpicklingError: invalid load key, '6'.
```

Hast du eine Idee wo das Problem liegt?

Liebe Grüße!

**Comment by devmount** [comment]
Hi Marisa,
spannendes Projekt! Ich habe das Model damals im word2vec C binary Format gespeichert, es muss auch in diesem Format geladen werden, damit es funktioniert. Ich habe deinen Code geprüft, du lädst das Model per

```python
vector_model = gensim.models.Word2Vec.load(w2v_model).wv
```

Damals habe ich es so geladen:
https://github.com/devmount/GermanWordEmbeddings/blob/e39c8bf2d75c7758d93a8c0211c232533928fb24/evaluation.py#L332

Ich habe mal [in die Doku](https://radimrehurek.com/gensim/models/word2vec.html#usage-examples) geschaut und gesehen, dass das C binary Format anscheinend noch unterstützt wird. Hier ein Beispiel für das Laden in deinem Fall (ungetestet):

```python
from gensim.test.utils import datapath
vector_model = gensim.models.KeyedVectors.load_word2vec_format(datapath(w2v_model), binary=True)
```
