### ISSUE TITLE
Error trying to load "german.model"

### ISSUE THREAD

**Issue by davidsbatista** [devmount/GermanWordEmbeddings#5]
Hi! 

Thanks for making this embeddings available :) With which version of gensim did you save the model? I'm having problems loading the model, e.g.:

```
>>> from gensim.models import Word2Vec
>>> model = Word2Vec.load("german.model")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dsbatista/virtual_envs/python2/lib/python2.7/site-packages/gensim/models/word2vec.py", line 1412, in load
    model = super(Word2Vec, cls).load(*args, **kwargs)
  File "/Users/dsbatista/virtual_envs/python2/lib/python2.7/site-packages/gensim/utils.py", line 276, in load
    obj = unpickle(fname)
  File "/Users/dsbatista/virtual_envs/python2/lib/python2.7/site-packages/gensim/utils.py", line 940, in unpickle
    return _pickle.loads(f.read())
cPickle.UnpicklingError: invalid load key, '6'.
```

```
>>> gensim.__version__
'2.3.0'
```

Python 2.7.10

**Comment by devmount** [comment]
You're welcome ;) I saved the model as binary - respectively you have to load it like this:

    model = gensim.models.KeyedVectors.load_word2vec_format("german.model", binary=True)

Let me know if you have an further problems and thanks for using this project!

**Comment by davidsbatista** [comment]
Thanks got it working :)
